grafana:
  admin:
    existingSecret: grafana-admin
    userKey: admin-user
    passwordKey: admin-password
  persistence: {enabled: false}
  resources:
    requests: {cpu: 50m, memory: 128Mi}
    limits: {memory: 256Mi}
prometheus:
  prometheusSpec:
    retention: 3d
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    resources:
      requests: {cpu: 100m, memory: 400Mi}
      limits: {memory: 900Mi}
alertmanager:
  alertmanagerSpec:
    secrets: [alertmanager-slack]
    resources:
      requests: {cpu: 20m, memory: 48Mi}
      limits: {memory: 128Mi}
  config:
    route:
      receiver: chat
      group_by: [alertname, namespace]
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 4h
    receivers:
      - name: "null"
      - name: chat
        slack_configs:
          - api_url_file: /etc/alertmanager/secrets/alertmanager-slack/url
            channel: "#nsp-alerts"
            send_resolved: true
kubeEtcd: {enabled: false}
kubeControllerManager: {enabled: false}
kubeScheduler: {enabled: false}
kubeProxy: {enabled: false}
